<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('productos')->insert([
            // --- Medicamentos ---
            [
                'nombre' => 'Ibuprofeno 600mg',
                'descripcion' => 'Antiinflamatorio no esteroide, 20 comprimidos recubiertos',
                'precio_compra' => 250.00,
                'precio_venta' => 520.00,
                'stock_inicial' => 200,
                'stock_actual' => 185,
                'stock_minimo' => 30,
                'caducidad' => '2026-12-31',
                'id_categoria' => 1,
                'id_proveedor' => 5,
            ],
            [
                'nombre' => 'Paracetamol 500mg',
                'descripcion' => 'Analgésico y antitérmico, 30 comprimidos',
                'precio_compra' => 180.00,
                'precio_venta' => 380.00,
                'stock_inicial' => 300,
                'stock_actual' => 278,
                'stock_minimo' => 50,
                'caducidad' => '2026-11-30',
                'id_categoria' => 1,
                'id_proveedor' => 5,
            ],
            [
                'nombre' => 'Amoxicilina 500mg',
                'descripcion' => 'Antibiótico de amplio espectro, 21 comprimidos',
                'precio_compra' => 420.00,
                'precio_venta' => 890.00,
                'stock_inicial' => 150,
                'stock_actual' => 142,
                'stock_minimo' => 25,
                'caducidad' => '2026-06-15',
                'id_categoria' => 1,
                'id_proveedor' => 7,
            ],
            [
                'nombre' => 'Omeprazol 20mg',
                'descripcion' => 'Inhibidor de bomba de protones, 28 cápsulas',
                'precio_compra' => 350.00,
                'precio_venta' => 750.00,
                'stock_inicial' => 180,
                'stock_actual' => 165,
                'stock_minimo' => 30,
                'caducidad' => '2027-03-20',
                'id_categoria' => 1,
                'id_proveedor' => 8,
            ],
            [
                'nombre' => 'Losartán 50mg',
                'descripcion' => 'Antihipertensivo, 30 comprimidos',
                'precio_compra' => 290.00,
                'precio_venta' => 620.00,
                'stock_inicial' => 120,
                'stock_actual' => 108,
                'stock_minimo' => 20,
                'caducidad' => '2026-09-10',
                'id_categoria' => 1,
                'id_proveedor' => 9,
            ],
            [
                'nombre' => 'Betacort 0.05%',
                'descripcion' => 'Betametasona crema tópica 30g',
                'precio_compra' => 500.00,
                'precio_venta' => 1000.00,
                'stock_inicial' => 80,
                'stock_actual' => 72,
                'stock_minimo' => 15,
                'caducidad' => '2027-05-05',
                'id_categoria' => 1,
                'id_proveedor' => 5,
            ],
            [
                'nombre' => 'Minoxidil 5%',
                'descripcion' => 'Solución tópica para caída del cabello, 60ml',
                'precio_compra' => 1200.00,
                'precio_venta' => 2500.00,
                'stock_inicial' => 60,
                'stock_actual' => 55,
                'stock_minimo' => 10,
                'caducidad' => '2027-08-15',
                'id_categoria' => 1,
                'id_proveedor' => 1,
            ],
            [
                'nombre' => 'Salbutamol Inhalador',
                'descripcion' => 'Broncodilatador para asma, 200 dosis',
                'precio_compra' => 1800.00,
                'precio_venta' => 3800.00,
                'stock_inicial' => 40,
                'stock_actual' => 35,
                'stock_minimo' => 8,
                'caducidad' => '2026-05-20',
                'id_categoria' => 1,
                'id_proveedor' => 10,
            ],
            [
                'nombre' => 'Diclofenac 75mg',
                'descripcion' => 'Antiinflamatorio, 10 ampollas inyectables',
                'precio_compra' => 450.00,
                'precio_venta' => 950.00,
                'stock_inicial' => 90,
                'stock_actual' => 82,
                'stock_minimo' => 15,
                'caducidad' => '2026-10-30',
                'id_categoria' => 1,
                'id_proveedor' => 7,
            ],

            // --- Higiene Personal ---
            [
                'nombre' => 'Jabón Líquido Dove 400ml',
                'descripcion' => 'Jabón líquido de manos y cuerpo, 400ml',
                'precio_compra' => 280.00,
                'precio_venta' => 580.00,
                'stock_inicial' => 120,
                'stock_actual' => 110,
                'stock_minimo' => 25,
                'caducidad' => null,
                'id_categoria' => 2,
                'id_proveedor' => 3,
            ],
            [
                'nombre' => 'Desodorante Axe 150ml',
                'descripcion' => 'Desodorante aerosol Axe, 150ml',
                'precio_compra' => 190.00,
                'precio_venta' => 420.00,
                'stock_inicial' => 100,
                'stock_actual' => 88,
                'stock_minimo' => 20,
                'caducidad' => null,
                'id_categoria' => 2,
                'id_proveedor' => 13,
            ],
            [
                'nombre' => 'Shampoo Pantene 400ml',
                'descripcion' => 'Shampoo reparación completa, 400ml',
                'precio_compra' => 350.00,
                'precio_venta' => 750.00,
                'stock_inicial' => 85,
                'stock_actual' => 78,
                'stock_minimo' => 15,
                'caducidad' => null,
                'id_categoria' => 7,
                'id_proveedor' => 12,
            ],
            [
                'nombre' => 'Toallitas Húmedas 100u',
                'descripcion' => 'Toallitas húmedas baby, paquete 100 unidades',
                'precio_compra' => 120.00,
                'precio_venta' => 290.00,
                'stock_inicial' => 150,
                'stock_actual' => 140,
                'stock_minimo' => 30,
                'caducidad' => null,
                'id_categoria' => 3,
                'id_proveedor' => 12,
            ],

            // --- Cosméticos ---
            [
                'nombre' => 'Lápiz Labial Maybelline',
                'descripcion' => 'Labial color mate, tono nude, 4g',
                'precio_compra' => 450.00,
                'precio_venta' => 980.00,
                'stock_inicial' => 50,
                'stock_actual' => 45,
                'stock_minimo' => 10,
                'caducidad' => null,
                'id_categoria' => 4,
                'id_proveedor' => 2,
            ],
            [
                'nombre' => 'Base Líquida Vogue',
                'descripcion' => 'Base fluida cobertura natural, tono natural, 30ml',
                'precio_compra' => 380.00,
                'precio_venta' => 820.00,
                'stock_inicial' => 35,
                'stock_actual' => 30,
                'stock_minimo' => 8,
                'caducidad' => null,
                'id_categoria' => 4,
                'id_proveedor' => 2,
            ],

            // --- Perfumería ---
            [
                'nombre' => 'Colonia Paco Rabanne Invictus 100ml',
                'descripcion' => 'Perfume masculino, 100ml',
                'precio_compra' => 3500.00,
                'precio_venta' => 7200.00,
                'stock_inicial' => 20,
                'stock_actual' => 18,
                'stock_minimo' => 5,
                'caducidad' => null,
                'id_categoria' => 5,
                'id_proveedor' => 2,
            ],
            [
                'nombre' => 'Colonia Carolina Herrera Good Girl 80ml',
                'descripcion' => 'Perfume femenino, 80ml',
                'precio_compra' => 4200.00,
                'precio_venta' => 8500.00,
                'stock_inicial' => 15,
                'stock_actual' => 12,
                'stock_minimo' => 3,
                'caducidad' => null,
                'id_categoria' => 5,
                'id_proveedor' => 2,
            ],

            // --- Cuidado Facial ---
            [
                'nombre' => 'Crema Facial Dove 50ml',
                'descripcion' => 'Crema humectante facial, 50ml',
                'precio_compra' => 320.00,
                'precio_venta' => 700.00,
                'stock_inicial' => 70,
                'stock_actual' => 62,
                'stock_minimo' => 15,
                'caducidad' => null,
                'id_categoria' => 6,
                'id_proveedor' => 3,
            ],
            [
                'nombre' => 'Protector Solar FPS 50 120ml',
                'descripcion' => 'Protector solar facial y corporal, 120ml',
                'precio_compra' => 600.00,
                'precio_venta' => 1300.00,
                'stock_inicial' => 45,
                'stock_actual' => 40,
                'stock_minimo' => 10,
                'caducidad' => null,
                'id_categoria' => 6,
                'id_proveedor' => 13,
            ],

            // --- Vitaminas y Suplementos ---
            [
                'nombre' => 'Vitamina C 1000mg efervescente',
                'descripcion' => 'Vitamina C efervescente, 30 comprimidos',
                'precio_compra' => 420.00,
                'precio_venta' => 900.00,
                'stock_inicial' => 100,
                'stock_actual' => 92,
                'stock_minimo' => 20,
                'caducidad' => '2026-08-20',
                'id_categoria' => 8,
                'id_proveedor' => 5,
            ],
            [
                'nombre' => 'Complejo B x60 comprimidos',
                'descripcion' => 'Complejo vitamínico B1, B6, B12, 60 comprimidos',
                'precio_compra' => 520.00,
                'precio_venta' => 1100.00,
                'stock_inicial' => 80,
                'stock_actual' => 73,
                'stock_minimo' => 15,
                'caducidad' => '2026-07-15',
                'id_categoria' => 8,
                'id_proveedor' => 9,
            ],
            [
                'nombre' => 'Calcio + Vitamina D x30',
                'descripcion' => 'Suplemento de calcio con vitamina D, 30 comprimidos',
                'precio_compra' => 380.00,
                'precio_venta' => 820.00,
                'stock_inicial' => 90,
                'stock_actual' => 85,
                'stock_minimo' => 15,
                'caducidad' => '2026-10-10',
                'id_categoria' => 8,
                'id_proveedor' => 8,
            ],

            // --- Primeros Auxilios ---
            [
                'nombre' => 'Alcohol Etílico 500ml',
                'descripcion' => 'Alcohol etílico 96°, 500ml',
                'precio_compra' => 110.00,
                'precio_venta' => 250.00,
                'stock_inicial' => 200,
                'stock_actual' => 195,
                'stock_minimo' => 40,
                'caducidad' => null,
                'id_categoria' => 9,
                'id_proveedor' => 1,
            ],
            [
                'nombre' => 'Venda Elástica 10cm x 5m',
                'descripcion' => 'Venda elástica adhesiva, 10cm x 5m',
                'precio_compra' => 180.00,
                'precio_venta' => 400.00,
                'stock_inicial' => 80,
                'stock_actual' => 75,
                'stock_minimo' => 15,
                'caducidad' => null,
                'id_categoria' => 9,
                'id_proveedor' => 1,
            ],
            [
                'nombre' => 'Curitas x20',
                'descripcion' => 'Apósitos adhesivos estériles, caja 20 unidades',
                'precio_compra' => 80.00,
                'precio_venta' => 190.00,
                'stock_inicial' => 250,
                'stock_actual' => 240,
                'stock_minimo' => 50,
                'caducidad' => null,
                'id_categoria' => 9,
                'id_proveedor' => 4,
            ],

            // --- Salud Bucal ---
            [
                'nombre' => 'Pasta Dental Colgate 90g',
                'descripcion' => 'Pasta dental Colgate Triple Acción, 90g',
                'precio_compra' => 130.00,
                'precio_venta' => 300.00,
                'stock_inicial' => 180,
                'stock_actual' => 170,
                'stock_minimo' => 30,
                'caducidad' => null,
                'id_categoria' => 11,
                'id_proveedor' => 12,
            ],
            [
                'nombre' => 'Cepillo Dental Oral-B',
                'descripcion' => 'Cepillo dental Oral-B, cerdas medias',
                'precio_compra' => 180.00,
                'precio_venta' => 420.00,
                'stock_inicial' => 100,
                'stock_actual' => 95,
                'stock_minimo' => 20,
                'caducidad' => null,
                'id_categoria' => 11,
                'id_proveedor' => 12,
            ],
            [
                'nombre' => 'Enjuague Bucal Listerine 250ml',
                'descripcion' => 'Enjuague bucal antibacterial, 250ml',
                'precio_compra' => 220.00,
                'precio_venta' => 480.00,
                'stock_inicial' => 75,
                'stock_actual' => 68,
                'stock_minimo' => 12,
                'caducidad' => null,
                'id_categoria' => 11,
                'id_proveedor' => 13,
            ],

            // --- Diabetes ---
            [
                'nombre' => 'Tiras Reactivas Accu-Chek x50',
                'descripcion' => 'Tiras reactivas para glucemia Accu-Chek Guide, 50u',
                'precio_compra' => 1800.00,
                'precio_venta' => 3800.00,
                'stock_inicial' => 30,
                'stock_actual' => 25,
                'stock_minimo' => 8,
                'caducidad' => '2026-04-15',
                'id_categoria' => 12,
                'id_proveedor' => 6,
            ],
            [
                'nombre' => 'Metformina 850mg x60',
                'descripcion' => 'Antidiabético oral, 60 comprimidos',
                'precio_compra' => 320.00,
                'precio_venta' => 680.00,
                'stock_inicial' => 100,
                'stock_actual' => 95,
                'stock_minimo' => 20,
                'caducidad' => '2026-09-30',
                'id_categoria' => 12,
                'id_proveedor' => 7,
            ],

            // --- Cuidado Capilar ---
            [
                'nombre' => 'Acondicionador Pantene 400ml',
                'descripcion' => 'Acondicionador reparación completa, 400ml',
                'precio_compra' => 330.00,
                'precio_venta' => 710.00,
                'stock_inicial' => 80,
                'stock_actual' => 74,
                'stock_minimo' => 15,
                'caducidad' => null,
                'id_categoria' => 7,
                'id_proveedor' => 12,
            ],
            [
                'nombre' => 'Tinte Capilar Koleston 6.0',
                'descripcion' => 'Tinte capilar rubio oscuro, 60ml',
                'precio_compra' => 380.00,
                'precio_venta' => 820.00,
                'stock_inicial' => 40,
                'stock_actual' => 36,
                'stock_minimo' => 8,
                'caducidad' => null,
                'id_categoria' => 7,
                'id_proveedor' => 2,
            ],

            // --- Dermocosmética ---
            [
                'nombre' => 'La Roche Posay Cicaplast 40ml',
                'descripcion' => 'Bálsama reparador para piel irritada, 40ml',
                'precio_compra' => 850.00,
                'precio_venta' => 1800.00,
                'stock_inicial' => 25,
                'stock_actual' => 22,
                'stock_minimo' => 5,
                'caducidad' => null,
                'id_categoria' => 13,
                'id_proveedor' => 10,
            ],
            [
                'nombre' => 'Eucerin PH5 Crem 75ml',
                'descripcion' => 'Crema corporal protectora Eucerin PH5, 75ml',
                'precio_compra' => 650.00,
                'precio_venta' => 1400.00,
                'stock_inicial' => 30,
                'stock_actual' => 27,
                'stock_minimo' => 6,
                'caducidad' => null,
                'id_categoria' => 13,
                'id_proveedor' => 6,
            ],
        ]);
    }
}
